baseURL = 'https://beyondvoid.me'
languageCode = 'en-us'
title = 'Hankkkkkabom'
theme = 'maverick'

paginate = 3

[permalinks]
pages = "/:slug"

# [params]
# logo = '/favicon.ico'
# description = "A minimal hugo theme focus on content"
# author = 'Calvin Tran'
[params.meta]
# favicon = false

[params.comments]
enabled = true
githubRepo = 'hank8451/hankchcblog'
theme = 'github-light'


[menu]
# [[menu.main]]
# identifier = "about"
# name = "About"
# url = "/about/"
# weight = "-110"
[[menu.main]]
identifier = "posts"
name = "Posts"
pageRef = "/posts"
weight = -200


[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokailight'
tabWidth = 4

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[outputFormats.JSON]
mediatype = "application/json"
baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
