baseURL = 'https://beyondvoid.me'
languageCode = 'en-us'
title = 'NIP Blog'
theme = 'PaperMod'

[permalinks]
pages = "/:slug"

# [params]
# logo = '/favicon.ico'
# description = "A minimal hugo theme focus on content"
# author = 'Calvin Tran'
[params.meta]
# favicon = false

[params.comments]
enabled = true
githubRepo = 'hank8451/hankchcblog'
theme = 'github-light'


[menu]
# [[menu.main]]
# identifier = "about"
# name = "About"
# url = "/about/"
# weight = "-110"
[[menu.main]]
identifier = "posts"
name = "Posts"
pageRef = "/posts"
weight = -200


[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]

ignoreErrors = ["error-remote-getjson"]
